# Generated by Django 3.2.19 on 2024-06-27 12:30

from django.db import migrations
import django.db.models.deletion
import djangoplugins.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoplugins', '0002_add_id_to_plugins_uniq'),
        ('documents', '0002_auto_20161018_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='definition',
            field=djangoplugins.fields.PluginField(limit_choices_to={'point__pythonpath': 'jane.documents.plugins.DocumentPluginPoint'}, on_delete=django.db.models.deletion.CASCADE, related_name='definition', to='djangoplugins.plugin'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='indexer',
            field=djangoplugins.fields.PluginField(limit_choices_to={'point__pythonpath': 'jane.documents.plugins.IndexerPluginPoint'}, on_delete=django.db.models.deletion.CASCADE, related_name='indexer', to='djangoplugins.plugin'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='retrieve_permissions',
            field=djangoplugins.fields.ManyPluginField(blank=True, limit_choices_to={'point__pythonpath': 'jane.documents.plugins.RetrievePermissionPluginPoint'}, related_name='retrieve_permissions', to='djangoplugins.Plugin'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='upload_permissions',
            field=djangoplugins.fields.ManyPluginField(blank=True, limit_choices_to={'point__pythonpath': 'jane.documents.plugins.UploadPermissionPluginPoint'}, related_name='upload_permissions', to='djangoplugins.Plugin'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='validators',
            field=djangoplugins.fields.ManyPluginField(blank=True, limit_choices_to={'point__pythonpath': 'jane.documents.plugins.ValidatorPluginPoint'}, related_name='validators', to='djangoplugins.Plugin'),
        ),
    ]
