# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentindexattachment_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentindex',
            name='stations',
            field=models.ManyToManyField(through='documents.DocumentIndexAttachment', to='documents.Document'),
        ),
    ]
